name: Pytest run

on:
  push:
    branches: [ "main" ]
    inputs:
      auth_key:
        description: "Ключ авторизации для получения токена"
        required: true
        type: string
      
  pull_request:
    branches: [ "main" ]
    inputs:
      auth_key:
        description: "Ключ авторизации для получения токена"
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Allure CLI
      run: npm install -g allure-commandline
  
    - name: Test with pytest
      env:
        AUTH_KEY: ${{ secrets.AUTH_KEY_SECRET }}
      run: |
        pytest --alluredir=./allure_results

    - name: Generate Allure report
      run: |
        allure generate -c -o ./allure-report ./allure_results

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report/
        retention-days: 7

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        commit_message: 'Deploy Allure report'
